---
- name: Network Basic Demos
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - include_vars: ../defaults/main.yml

    - include_tasks: ../tasks/push_intf_l3.yml
      tags: [push_intf_l3, push_intf] 

