---
- name: Network Basic Demos
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - include_vars: defaults/main.yml

    - include_tasks: tasks/parse_intf.yml
      tags: [parse_intf, netbox]
