---
- name: Network Basic Demos
  hosts: switch
  gather_facts: false
  connection: local
  tasks:
    - include_vars: ../defaults/main.yml

    - include_tasks: ../tasks/push_intf_l2_survey.yml
      tags: [l2survey]
      when: inventory_hostname in groups['switch']
